CREATE DATABASE ms_user;

USE ms_user;

CREATE TABLE users (
  id INTEGER AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE outbox (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	type VARCHAR(50) NOT NULL,
	aggregate_type VARCHAR(50) NOT NULL,
	aggregate_id INTEGER NOT NULL,
	payload text NOT NULL
);
